### ISSUE TITLE
Subscriptions in client

### ISSUE THREAD

**Issue by ysangkok** [kyuupichan/aiorpcX#1]
It looks like aiorpcx doesn't support subscribing and getting multiple replies in an asyncio.Queue or similar.

Just a feature request :)

**Comment by kyuupichan** [comment]
Can you elaborate?

**Comment by ysangkok** [comment]
Something like this: https://github.com/coinkite/connectrum/blob/01df24124d4b17ce77ef040c97b46f76b03865a1/examples/subscribe.py#L30

Doesn't seem like there is client support for receiving an unending stream in aiorpcx. The notification support is for the server, not the client. `.result()` always returns a single value, not a Queue.

**Comment by kyuupichan** [comment]
Works for me:

```
$ python3 test.py
INFO:client:connected
INFO:client:server.version: ['ElectrumX 1.7', '1.4']
INFO:client:subscription response: {'hex': '000000209cacec1ee3b59914bf6ec2c5e81f5776f782642e17141e0000000000000000009884229c9cd29d1b999d34e3cd0346beb87e48c0087a43bb7f311fa553bdad4e613a5b5b2f17021811f9811d', 'height': 540806}
INFO:client:notified of new header: {'hex': '000000200ce9fef39ee7f3c37976d9f1087c791e822ef3ccf05aa5010000000000000000b981a74048bfdd28de78b9d2ac6b479afdd3056883eb71c9fe429031bd693f78a73c5b5ba81c0218d893b5db', 'height': 540807}
INFO:client:notified of new header: {'hex': '00000020fec11d1d1403c6c63a3f37cdce9863c2a4a264ffd1911801000000000000000049ac5ee17ff15547c1f3813064c697024fddf2f8d4c32f5e1613aae89fe9fdf5af3c5b5b711f0218cb49fb80', 'height': 540808}
```

Here's the code:

```
import asyncio
import aiorpcx
import ssl
import logging

logger = logging.getLogger('client')

class CashSession(aiorpcx.ClientSession):
    def header_notification(self, header):
        logger.info(f'notified of new header: {header}')

    def notification_handler(self, method):
        # We subscribe so might be unlucky enough to get a notification...
        if method == 'blockchain.headers.subscribe':
            return self.header_notification
        return None


async def main():
    sslc = ssl.SSLContext(ssl.PROTOCOL_TLS)
    event = asyncio.Event()
    async with CashSession('bch.electrumx.cash', 50002, ssl=sslc) as session:
        logger.info('connected')
        result = await session.send_request('server.version', ['test', '1.4'])
        logger.info(f'server.version: {result}')
        result = await session.send_request('blockchain.headers.subscribe')
        logger.info(f'subscription response: {result}')
        await event.wait()


logging.basicConfig(level=logging.INFO)
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

```

**Comment by kyuupichan** [comment]
I'm not sure why you feel you need a queue?

I'm more inclined to get rid of the callbacks (never been a fan of that in the API) and instead have an async method next_notification() and another next_message() that block until there is a notification or message.

**Comment by kyuupichan** [comment]
Though I guess that API could be a queue instead.  I'll have to think about it.

**Comment by ysangkok** [comment]
Works great, the problem was that the notification handler will never be called if I busy wait. Thanks for the example, it helped.

Queues are nicer than handlers, I think, considering that they wouldn't need subclassing. But I don't know how to make the API nice since I don't know if you want to assume that notification replies always include the arguments from the subscription. If you assume they do, there could be an asyncgen or queue returned with each subscription.

**Comment by kyuupichan** [comment]
Yeah if you busy wait you block anything else getting done :)

I'm redoing the whole aiorpcX API based on what I've learnt since I wrote it; it should be nicer when I release that in a week or two.  It's API will be mostly async which will provide one way for request processing to provide backpressure to the network.  It will use a queue internally but that's an implementation detail.

I'm not sure about the handler stuff yet...

**Comment by kyuupichan** [comment]
No, I cannot make that assumption, it's not true of JSON RPC.  There is no requirement that a notification come from a subscription at all, for example...
