### ISSUE TITLE
include LICENSE into pypi tarball

### ISSUE THREAD

**Issue by ignatenkobrain** [kyuupichan/aiorpcX#11]
And publish new version, please.

Thanks in advance!

**Comment by kyuupichan** [comment]
Pull request?

**Comment by kyuupichan** [comment]
I see little evidence this is standard for Python libraries

**Comment by Conan-Kudo** [comment]
You do require the full license, since the license text can vary for "MIT" license.

**Comment by rapgro** [comment]
We found BSD (2-clause) simplified and Expat licenses with the package review.

**Comment by Conan-Kudo** [comment]
They have to be included.
