### ISSUE TITLE
pypi is missing tests

### ISSUE THREAD

**Issue by jirislaby** [kyuupichan/aiorpcX#14]
Could you add tests to the pypi package too, so that we can run the tests on the distribution side?

**Comment by kyuupichan** [comment]
I'm not inclined to do so, no.  Can you point to major packages that do so?

**Comment by jirislaby** [comment]
Sorry, I have no idea. I was asked by openSUSE packagers to ask you, as there has to be tests run during packaging. Instead of pypi, they switched to the github release to have them in.
