### ISSUE TITLE
ProtocolError logs an error without a way to handle it

### ISSUE THREAD

**Issue by erasmospunk** [kyuupichan/aiorpcX#4]
When getting malformed JSON in `SessionBase::_process_messages()`, the ProtocolError is just being logged without a way to handle it.

When pressing enter in a telnet connection to ElectrumX, it logs:
```
2018-08-09 17:27:40,889:ERROR:ElectrumX:[2] ProtocolError(-32700, "cannot decode JSON: JSONDecodeError('Expecting value: line 1 column 2 (char 1)',)")
```
Previously it was disconnecting the client.

**Comment by kyuupichan** [comment]
I deliberately removed the disconnect behaviour quite a long time ago (i.e. at least 3 months ago).   Is it the logging you don't like, or do you think the disconnect is better?  Or you're just bringing the change in behaviour to my attention?

**Comment by kyuupichan** [comment]
I think the logging could get annoying; perhaps it should just silently increment the error count?

**Comment by erasmospunk** [comment]
I noticed it when doing debugging with telnet.

I prefer a rigid, disconnect (and return an error to client) on unexpected input even though it is pain when manually debugging.

It is worrisome because it produces a 151 byte log entry for each `\n` byte sent and you can fit tens of thousands in a single IP packet. You can create a 1GB log by sending about 6.6MB of data.

**Comment by Ali8263** [comment]
It is worrisome because it produces a 151 byte log entry for each \n byte sent and you can fit tens of thousands in a single IP packet. You can create a 1GB log by sending about 6.6MB of data.
